server:
  port: 9091
  servlet:
    context-path: /api/v1/issue-management-service

github:
  user-detail-url: https://api.github.com/repos/EthicalML/awesome-production-machine-learning/contributors

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/developer_iq_tracker?readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
